import {
  pgTable,
  text,
  timestamp,
  integer,
  primaryKey,
  pgEnum,
} from "drizzle-orm/pg-core";

// ========================
// Enums
// ========================
export const planEnum = pgEnum("plan", ["FREE", "PRO", "ULTRA"]);

// ========================
// Users
// ========================
export const users = pgTable("user", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").unique(),
  emailVerified: timestamp("emailVerified", { mode: "date" }),
  image: text("image"),
  plan: planEnum("plan").default("FREE").notNull(),
  generationCount: integer("generation_count").default(0).notNull(),
  lastResetAt: timestamp("last_reset_at", { mode: "date" }).defaultNow(),
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
});

// ========================
// Accounts (OAuth)
// ========================
export const accounts = pgTable(
  "account",
  {
    userId: text("userId")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("providerAccountId").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (account) => [
    primaryKey({
      columns: [account.provider, account.providerAccountId],
    }),
  ]
);

// ========================
// Sessions
// ========================
export const sessions = pgTable("session", {
  sessionToken: text("sessionToken").primaryKey(),
  userId: text("userId")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { mode: "date" }).notNull(),
});

// ========================
// Verification Tokens (Email Magic Links)
// ========================
export const verificationTokens = pgTable(
  "verificationToken",
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (verificationToken) => [
    primaryKey({
      columns: [verificationToken.identifier, verificationToken.token],
    }),
  ]
);

// ========================
// Proposals (History)
// ========================
export const proposals = pgTable("proposal", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  userId: text("userId")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  type: text("type").notNull(),
  content: text("content").notNull(), // The generated HTML or text
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow(),
});

// ========================
// Transactions (Midtrans)
// ========================
export const transactions = pgTable("transaction", {
  orderId: text("order_id").primaryKey(), // Generated by us, e.g., tx_...
  userId: text("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),
  plan: planEnum("plan").notNull(), // The plan they are buying
  grossAmount: integer("gross_amount").notNull(),
  status: text("status").default("pending").notNull(), // pending, settlement, expire, cancel
  snapToken: text("snap_token"),
  snapRedirectUrl: text("snap_redirect_url"),
  paymentType: text("payment_type"), // e.g., qris, gopay, bank_transfer
  createdAt: timestamp("created_at", { mode: "date" }).defaultNow(),
  updatedAt: timestamp("updated_at", { mode: "date" }).defaultNow(),
});
